In [61]:
from typing import Tuple
from functools import reduce
from operator import mul
import numpy as np

In [10]:
def read_input(day):
    with open(f"./input/day_{day}.txt") as f:
        return [l.strip() for l in f]
    
def quantify(iterable, pred):
    return sum(map(pred, iterable))

In [11]:
def solution_day_1():
    day_1_input = [int(i) for i in read_input(1)]
    sol_part_a = quantify(zip(day_1_input[0:], day_1_input[1:]), lambda x: x[1] > x[0])
    
    day_1_input = list(map(sum, (zip(day_1_input[0:], day_1_input[1:], day_1_input[2:]))))
    sol_part_b = quantify(zip(day_1_input[0:], day_1_input[1:]), lambda x: x[1] > x[0])
    
    return sol_part_a, sol_part_b

solution_day_1()

(1791, 1822)

In [47]:
def solution_day_2():
    initial_position = (0, 0)
    day_2_input = read_input(2)
    
    def tuple_sum(a, b):
        return [sum(x) for x in zip(a, b)]

    def val(s: str) -> int:
        return int(s.split(' ')[1])

    def transform_a(s: str) -> Tuple[int, int]:
        if s.startswith('forward'):
            return val(s), 0
        elif s.startswith('down'):
            return 0, val(s)
        else:
            return 0, -1 * val(s)
        
    def final_position(transform_fn):
         return reduce(tuple_sum, map(transform_fn, day_2_input), initial_position)
        
    sol_2_a = mul(*final_position(transform))
    
    def transform_b(current_pos, command) -> Tuple[int, int]:
        x = val(command)
        if command.startswith('forward'):
            return current_pos[0] + x, current_pos[1] + current_pos[2] * x, current_pos[2]
        elif command.startswith('down'):
            return current_pos[0], current_pos[1], current_pos[2] + x
        else:
            return current_pos[0], current_pos[1], current_pos[2] - x

    sol_2_b = mul(*reduce(transform_b, day_2_input, (0, 0, 0))[:-1])
    
    return sol_2_a, sol_2_b

solution_day_2()

(1714680, 1963088820)

In [49]:
sample_input_day_3 = [
'00100',
'11110',
'10110',
'10111',
'10101',
'01111',
'00111',
'11100',
'10000',
'11001',
'00010',
'01010']

In [107]:
def solution_day_3():
    def binary_array_to_int(arr):
        return int(''.join(arr.astype(int).astype(str)), 2)
    
    day_input = read_input(3)
    bits = np.array([[*(int(i) for i in l)] for l in day_input])

    gamma = (np.sum(bits, axis=0) > len(bits) / 2)
    epsilon = binary_array_to_int(gamma == False)
    gamma = binary_array_to_int(gamma)
    
    sol_a = gamma * epsilon

    def rating(bits, mode):
        bits = np.copy(bits)

        pos = 0

        while len(bits) > 1:
            bit_sum = bits[:, pos].sum()

            if bit_sum == len(bits) / 2: # 1 & 0 occur equally 
                if mode == 'most_common':
                    bit_criteria = 1
                else:
                    bit_criteria = 0
            else:
                if mode == 'most_common':
                    bit_criteria = int(bit_sum > len(bits) / 2)
                else:
                    bit_criteria = int(bit_sum < len(bits) / 2)

            bits = bits[bits[:, pos] == bit_criteria]
            pos += 1
    
        return binary_array_to_int(bits[0])
    
    
    return sol_a, rating(bits, 'most_common') * rating(bits, 'least_common')

solution_day_3()

(741950, 903810)

In [263]:
def solution_day_4():
    def read_input_4(day):
        def read_board(f):
            f.readline()

            return np.array([[int(i) for i in f.readline().strip().split(' ') if i != ''] for _ in range(5)])

        with open(f"./input/day_{day}.txt") as f:
            numbers = [int(i) for i in f.readline().strip().split(',')]
            boards = np.array([read_board(f) for _ in range(3)])

            return numbers, boards
        
    numbers, boards = read_input_4(4)

    board_markers = np.zeros_like(boards, dtype=bool)

    for i, n in enumerate(numbers):
        board_markers = np.logical_or(board_markers, boards == n)

        for ax in range(1, 3):
            if np.any(winner_index := np.sum(board_markers, axis=ax) == 5):
                scores = np.ma.masked_where(board_markers, boards).sum(axis=2).sum(axis=1)
                winning_score = scores[np.any(winner_index, axis=1)][0] * n

                return winning_score

In [264]:
solution_day_4()

52668

In [258]:
board_markers

array([[[False, False,  True,  True,  True],
        [False,  True,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]],

       [[False, False,  True,  True, False],
        [ True, False, False,  True,  True],
        [False, False,  True, False,  True],
        [False,  True, False,  True,  True],
        [ True,  True, False, False, False]],

       [[ True,  True,  True,  True,  True],
        [False, False, False,  True, False],
        [False, False,  True, False, False],
        [False,  True, False, False,  True],
        [ True,  True, False, False,  True]]])

In [259]:
winner_index

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [260]:
winning_score

4512

In [167]:
np.sum(board_markers, axis=2) == 5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [168]:
winner_index = np.sum(board_markers, axis=2) == 5

In [241]:
winner_index

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

array([False, False,  True])

In [ ]:
winner_index

In [229]:
np.ma.masked_where(board_markers, boards)

masked_array(
  data=[[[22, 13, --, --, --],
         [8, --, --, --, --],
         [--, --, --, 16, --],
         [6, 10, 3, 18, --],
         [1, 12, 20, 15, 19]],

        [[3, 15, --, --, 22],
         [--, 18, 13, --, --],
         [19, 8, --, 25, --],
         [20, --, 10, --, --],
         [--, --, 16, 12, 6]],

        [[--, --, --, --, --],
         [10, 16, 15, --, 19],
         [18, 8, --, 26, 20],
         [22, --, 13, 6, --],
         [--, --, 12, 3, --]]],
  mask=[[[False, False,  True,  True,  True],
         [False,  True,  True,  True,  True],
         [ True,  True,  True, False,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]],

        [[False, False,  True,  True, False],
         [ True, False, False,  True,  True],
         [False, False,  True, False,  True],
         [False,  True, False,  True,  True],
         [ True,  True, False, False, False]],

        [[ True,  True,  True,  True,  True],
         [False

masked_array(data=[163, 187, 188],
             mask=[False, False, False],
       fill_value=999999)

In [212]:
sum((80, 9, 23, 16, 9))

137